# Generated by Django 4.0.5 on 2022-06-27 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BusDet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('busno', models.IntegerField()),
                ('Departuretime', models.IntegerField()),
                ('Destinations', models.CharField(max_length=200)),
                ('Seatsavail', models.IntegerField()),
                ('Tickcost', models.IntegerField()),
            ],
        ),
    ]
